name: Vangers MacOS Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, 60fps ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: update repos
      run: brew update
    - name: install libs
      run: brew install git ninja cmake sdl2 sdl2_net libogg libvorbis nasm yasm dylibbundler
    - name: clunk -- download lib
      run: git clone --depth 1 https://github.com/stalkerg/clunk.git clunk
    - name: clunk -- create build dir
      run: mkdir clunk/build
    - name: clunk -- build and install
      run: cmake -DCMAKE_INSTALL_PREFIX=/usr/local -G Ninja .. && ninja && sudo ninja install
      working-directory: clunk/build
    - name: ffmpeg -- download
      run: git clone --depth 1 --branch n4.2.2 https://git.ffmpeg.org/ffmpeg.git ffmpeg
    - name: ffmpeg -- configure
      run: ./configure --enable-shared --prefix=/usr/local
        --disable-everything
        --enable-swscale
        --enable-zlib
        --enable-demuxer=avi,rawvideo
        --enable-decoder=png,rawvideo
        --enable-parser=png
        --enable-protocol=file
        --disable-d3d11va
        --disable-dxva2
        --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg
        --disable-static --disable-bzlib --disable-libopenjpeg --disable-iconv
      working-directory: ffmpeg
    - name: ffmpeg -- build and install
      run: |
        make -j4
        sudo make install
      working-directory: ffmpeg
    - name: configure
      run: mkdir build && cd build && cmake -G Ninja ..
    - name: make
      run: ninja
      working-directory: build
    - name: vangers -- prepare release folder
      run: |
        cp -L /usr/local/lib/libSDL2-2.0.0.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libSDL2_net-2.0.0.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libavcodec.58.54.100.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libavformat.58.29.100.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libavutil.56.31.100.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libogg.0.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libvorbis.0.dylib Vangers.app/Contents/Libs/
        cp -L /usr/local/lib/libvorbisfile.3.dylib Vangers.app/Contents/Libs/
        cp clunk/build/libclunk.dylib Vangers.app/Contents/Libs/
        cp build/src/vangers Vangers.app/Contents/MacOS/Vangers
        dylibbundler -x Vangers.app/Contents/MacOS/Vangers
        strip Vangers.app/Contents/MacOS/Vangers
    - uses: actions/upload-artifact@v1
      with:
        name: Vangers
        path: Vangers.app