name: Vangers Windows 64bit Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, 60fps ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: install libs
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-ninja mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_net mingw-w64-x86_64-cmake mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis
    - uses: actions/checkout@v1
    - name: clunk -- download
      run: git clone --depth 1 https://github.com/stalkerg/clunk.git clunk
    - name: clunk -- create build dir
      run: msys2do mkdir clunk/build
    - name: clunk -- build and install
      run: |
        msys2do cmake -DCMAKE_INSTALL_PREFIX=/mingw64 -G Ninja ..
        msys2do ninja
        msys2do ninja install
      working-directory: clunk/build
    - name: ffmpeg -- download
      run: git clone --depth 1 --branch n4.2.2 https://git.ffmpeg.org/ffmpeg.git ffmpeg
    - name: ffmpeg -- configure
      run: msys2do ./configure --enable-shared --prefix=/mingw64
        --disable-everything
        --enable-swscale
        --enable-zlib
        --enable-demuxer=avi,rawvideo
        --enable-decoder=png,rawvideo
        --enable-parser=png
        --enable-protocol=file
        --disable-d3d11va
        --disable-dxva2
        --disable-doc --disable-ffplay --disable-ffprobe --disable-ffmpeg
        --disable-static --disable-bzlib --disable-libopenjpeg --disable-iconv
      working-directory: ffmpeg
    - name: clunk -- build and install
      run: |
        msys2do make
        msys2do make install
      working-directory: ffmpeg
    - name: create build dir
      run: msys2do mkdir build
    - name: configure
      run: msys2do cmake -G Ninja ..
      working-directory: build
    - name: make
      run: msys2do ninja
      working-directory: build
