name: Vangers Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, 60fps ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW64
    - name: install libs
      run: msys2do pacman --noconfirm -S mingw-w64-x86_64-SDL2 mingw-w64-x86_64-SDL2_net cmake mingw-w64-x86_64-libogg mingw-w64-x86_64-libvorbis mingw-w64-x86_64-ffmpeg
    - uses: actions/checkout@v1
    - name: clunk download lib
      run: git clone --depth 1 https://github.com/stalkerg/clunk.git clunk
      working-directory: /tmp
    - name: clunk build and install
      run: cmake -DCMAKE_INSTALL_PREFIX=/usr . && make && sudo make install
      working-directory: /tmp/clunk
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
      working-directory: build
